# Why Numpy
Is used for performing numerical operations like array addition, subtraction, multiplication, to create some random numbers, create
dummy values, etc

In [1]:
!pip install numpy 

In [2]:
import numpy as np

##  List vs Array
### List cannot perform element-wise operations where Arrays can perform elementwise operations.

In [3]:
scores=[95,96,90,98,90,95,33,36]

In [4]:
scores+2

TypeError: can only concatenate list (not "int") to list

In [5]:
scores[0]+2

97

In [6]:
for i in scores:
    i+2
    scores.append(i)

KeyboardInterrupt: 

In [7]:
arr=np.array([95,96,90,98,90,95,33,36])

In [8]:
arr

array([95, 96, 90, 98, 90, 95, 33, 36])

In [9]:
arr+2

array([ 97,  98,  92, 100,  92,  97,  35,  38])

### List is Heteregenous and Arrays are Homogenous

In [10]:
scores=[90,80,88]

In [11]:
scores

[90, 80, 88]

In [13]:
scores_1=[90,80.5,88]

In [14]:
scores_1

[90, 80.5, 88]

In [15]:
arr=np.array([60,80,90])

In [16]:
arr

array([60, 80, 90])

In [17]:
arr_1=np.array([60,80.5,90])

In [18]:
arr_1

array([60. , 80.5, 90. ])

In [19]:
arr_2=np.array([60,80.5,"90"])

In [20]:
arr_2

array(['60', '80.5', '90'], dtype='<U32')

## Create 1D array

In [21]:
arr_1=np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_1.ndim

1

## Create 2D array

In [25]:
arr_2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [26]:
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
arr_2.ndim

2

## Create 3D array

In [28]:
arr_3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [29]:
arr_3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [30]:
arr_3.ndim

3

In [38]:
arr_4=np.array([[1,2,3],[5,6,7],[8,9,10],[11,12.0,13]])

In [39]:
arr_4

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.],
       [11., 12., 13.]])

In [34]:
arr_4.ndim

2

In [35]:
arr_4

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [40]:
arr_4[2][1]=np.nan

In [41]:
arr_4

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 8., nan, 10.],
       [11., 12., 13.]])

In [43]:
arr_4[3]=np.nan

In [44]:
arr_4

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 8., nan, 10.],
       [nan, nan, nan]])

In [55]:
arr_5=np.array([1,2,3,8,9,4,5,6,8,90])

In [48]:
arr_5.mean()

13.6

In [49]:
arr_5.max()

90

In [50]:
arr_5.min()

1

In [51]:
arr_5.std()

25.593749236874228

In [52]:
arr_5.sort()

In [53]:
arr_5

array([ 1,  2,  3,  4,  5,  6,  8,  8,  9, 90])

In [57]:
arr_5.argmax()

9

In [58]:
arr_5=np.array([1,2,3,8,9,4,500,5,6,8,90])

In [59]:
arr_5.max()

500

In [60]:
arr_5.argmax()

6

In [61]:
arr_5.cumsum()

array([  1,   3,   6,  14,  23,  27, 527, 532, 538, 546, 636])

In [ ]:
arr_5.

In [67]:
arr_2.ndim

2

In [65]:
arr_6=arr_2.flatten()

In [68]:
arr_6.ndim

1

In [70]:
np.linspace(1,11,50)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [71]:
1.20408163-1.

0.2040816299999999

In [72]:
 1.40816327-1.20408163

0.20408164000000006

In [75]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [79]:
np.random.rand(10,5)

array([[0.43961002, 0.24932845, 0.1414761 , 0.80711042, 0.31711299],
       [0.62692472, 0.52214879, 0.91225128, 0.10183828, 0.03633324],
       [0.23324522, 0.16603494, 0.14099336, 0.67670435, 0.18292453],
       [0.71536684, 0.49610574, 0.61928416, 0.36574403, 0.18910282],
       [0.5948218 , 0.97515238, 0.91634729, 0.1933487 , 0.66081031],
       [0.42988136, 0.94468115, 0.28585534, 0.03207908, 0.20072535],
       [0.27654694, 0.64862177, 0.37705929, 0.94121144, 0.73642161],
       [0.31465076, 0.77859253, 0.36716474, 0.3372899 , 0.31973731],
       [0.76380135, 0.26061454, 0.0835396 , 0.73518387, 0.0091568 ],
       [0.50106449, 0.1060135 , 0.99432692, 0.58467355, 0.03788427]])

In [89]:
np.random.seed(50)
np.random.rand(10,5)

array([[0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ],
       [0.99657423, 0.4081972 , 0.77189399, 0.76053669, 0.31000935],
       [0.3465412 , 0.35176482, 0.14546686, 0.97266468, 0.90917844],
       [0.5599571 , 0.31359075, 0.88820004, 0.67457307, 0.39108745],
       [0.50718412, 0.5241035 , 0.92800093, 0.57137307, 0.66833757],
       [0.05225869, 0.3270573 , 0.05640164, 0.17982769, 0.92593317],
       [0.93801522, 0.71409271, 0.73268761, 0.46174768, 0.93132927],
       [0.40642024, 0.68320577, 0.64991587, 0.59876518, 0.22203939],
       [0.68235717, 0.8780563 , 0.79671726, 0.43200225, 0.91787822],
       [0.78183368, 0.72575028, 0.12485469, 0.91630845, 0.38771099]])

In [116]:

np.random.randint(1,90,50)

array([63, 56, 76, 13, 15, 20, 27, 20, 73, 40,  5, 53, 31, 30, 31, 33, 29,
       20, 68, 87, 61, 56, 86, 57, 67,  1, 61,  4, 24, 13, 36, 79, 70, 29,
       72, 55, 58, 11, 47, 49, 21, 52,  8, 43, 88, 69, 67, 13, 61, 81])

In [121]:
np.random.randn(2,10)

array([[ 2.47565551, -0.09218666,  0.54007999, -0.11632693, -0.27501822,
         1.03799786, -0.08114915,  0.41109738, -0.26913957, -0.37116932],
       [ 0.81512767, -0.51004318,  0.27614424, -1.53067679,  0.02632716,
        -0.50225538,  0.47446428, -0.6801921 , -2.06128195, -0.37455518]])

In [ ]:
np.random.randn()